version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0-beta.6
    - 5.1.0
    - 5.2.0
    - 5.3.0
    - 5.3.1
  - dependency-name: html-loader
    versions:
    - 2.0.0
    - 2.1.0
    - 2.1.1
    - 2.1.2
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.13.5
  - dependency-name: source-map-loader
    versions:
    - 2.0.1
  - dependency-name: "@babel/plugin-proposal-export-namespace-from"
    versions:
    - 7.12.13
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-export-default-from"
    versions:
    - 7.12.13
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
